### PR TITLE
Remove legacy autor role from access.php

### LINKED ISSUE #1: Installation Issue
During the installation the following error occurs:
Upgrading to new version
mod_mootimeter
Incorrect legacy role definition for type: autor

[More information about this error](https://docs.moodle.org/402/en/error/moodle/invalidlegacy)

Debug info:
Error code: invalidlegacy×Dismiss this notification
Stack trace:
line 1202 of /lib/accesslib.php: moodle_exception thrown
line 2396 of /lib/accesslib.php: call to assign_legacy_capabilities()
line 648 of /lib/upgradelib.php: call to update_capabilities()
line 933 of /lib/upgradelib.php: call to upgrade_component_updated()
line 687 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1974 of /lib/upgradelib.php: call to upgrade_plugins()
line 726 of /admin/index.php: call to upgrade_noncore()
×Dismiss this notification

### PR DESCRIPTION
**Pull request by NJahreis**
fixes #1

### CODE REVIEW

File: db/access.php [hunk 1]
```diff
@@ -46,8 +46,7 @@
         'contextlevel' => CONTEXT_MODULE,
         'archetypes' => [
             'editingteacher' => CAP_ALLOW,
-            'manager' => CAP_ALLOW,
-            'autor' => CAP_ALLOW,
+            'manager' => CAP_ALLOW
```
Comment (PM84) [inline db/access.php:49]:
```suggestion
            'manager' => CAP_ALLOW,
```
